#!/usr/bin/env python
import numpy as np
import pandas as pd

HMAX = 1280
df = pd.read_table( 'raw-png.dat', delim_whitespace=True
                  , skipinitialspace=True, index_col='filename', comment='#')
df = df.dropna()  # remove empty lines generated by comments
# filename (index) width height format compression alpha size quality depth
rm = df[(df.height > 1280) & (df.width > 1280)]
for f in rm.index:
  print 'cache/' + f[0:2] + '/' + f

